"""change_tariff_snapshot_to_jsonb_v2

Revision ID: 0862b894e9ac
Revises: 0e7f8248675f
Create Date: 2025-12-03 15:33:53.482298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0862b894e9ac'
down_revision: Union[str, Sequence[str], None] = '0e7f8248675f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appsettings', 'deepgram_voice_id')
    op.drop_column('appsettings', 'deepgram_api_key')
    op.alter_column('usage_sessions', 'tariff_snapshot',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='tariff_snapshot::jsonb')
    op.alter_column('user_accounts', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'student'::character varying"))
    op.alter_column('userprofile', 'preferences',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying"))
    op.alter_column('userprofile', 'preferred_tts_engine',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'openai'::character varying"))
    op.alter_column('userprofile', 'preferred_stt_engine',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'openai'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'preferred_stt_engine',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'openai'::character varying"))
    op.alter_column('userprofile', 'preferred_tts_engine',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'openai'::character varying"))
    op.alter_column('userprofile', 'preferences',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying"))
    op.alter_column('user_accounts', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'student'::character varying"))
    op.alter_column('usage_sessions', 'tariff_snapshot',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('appsettings', sa.Column('deepgram_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appsettings', sa.Column('deepgram_voice_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
