"""add_billing_tables

Revision ID: 0e7f8248675f
Revises: 
Create Date: 2025-12-03 14:35:38.250003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e7f8248675f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_amount_rub', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_user_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reward_minutes_for_referrer', sa.Integer(), nullable=False),
    sa.Column('reward_minutes_for_referred', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rewarded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_referred_user_id'), 'referrals', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_user_id'), 'referrals', ['referrer_user_id'], unique=False)
    op.create_table('usage_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('billed_minutes', sa.Integer(), nullable=False),
    sa.Column('billed_amount_rub', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tariff_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_sessions_user_account_id'), 'usage_sessions', ['user_account_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('minutes_delta', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_user_account_id'), 'wallet_transactions', ['user_account_id'], unique=False)
    # op.drop_column('appsettings', 'deepgram_voice_id')
    # op.drop_column('appsettings', 'deepgram_api_key')
    # op.alter_column('user_accounts', 'role',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False,
    #            existing_server_default=sa.text("'student'::character varying"))
    op.add_column('userprofile', sa.Column('minutes_balance', sa.Integer(), nullable=False, server_default=sa.text("0")))
    # op.alter_column('userprofile', 'preferences',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False,
    #            existing_server_default=sa.text("'{}'::character varying"))
    # op.alter_column('userprofile', 'preferred_tts_engine',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False,
    #            existing_server_default=sa.text("'openai'::character varying"))
    # op.alter_column('userprofile', 'preferred_stt_engine',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False,
    #            existing_server_default=sa.text("'openai'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'preferred_stt_engine',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'openai'::character varying"))
    op.alter_column('userprofile', 'preferred_tts_engine',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'openai'::character varying"))
    op.alter_column('userprofile', 'preferences',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying"))
    op.drop_column('userprofile', 'minutes_balance')
    op.alter_column('user_accounts', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'student'::character varying"))
    op.add_column('appsettings', sa.Column('deepgram_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appsettings', sa.Column('deepgram_voice_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_wallet_transactions_user_account_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_usage_sessions_user_account_id'), table_name='usage_sessions')
    op.drop_table('usage_sessions')
    op.drop_index(op.f('ix_referrals_referrer_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('billing_packages')
    # ### end Alembic commands ###
