"""add_language_mode_to_lesson_sessions

Revision ID: 2872afaa6467
Revises: 65532068a8dd
Create Date: 2025-12-03 16:46:20.064248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2872afaa6467'
down_revision: Union[str, Sequence[str], None] = '65532068a8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE lesson_sessions ADD COLUMN IF NOT EXISTS language_mode VARCHAR")
    op.execute("ALTER TABLE lesson_sessions ADD COLUMN IF NOT EXISTS language_level INTEGER")
    op.execute("ALTER TABLE lesson_sessions ADD COLUMN IF NOT EXISTS language_chosen_at TIMESTAMP")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE lesson_sessions DROP COLUMN IF EXISTS language_chosen_at")
    op.execute("ALTER TABLE lesson_sessions DROP COLUMN IF EXISTS language_level")
    op.execute("ALTER TABLE lesson_sessions DROP COLUMN IF EXISTS language_mode")
    # ### end Alembic commands ###
