"""add_language_mode_to_lesson_sessions

Revision ID: 2872afaa6467
Revises: 65532068a8dd
Create Date: 2025-12-03 16:46:20.064248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2872afaa6467'
down_revision: Union[str, Sequence[str], None] = '65532068a8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_sessions', sa.Column('language_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lesson_sessions', sa.Column('language_level', sa.Integer(), nullable=True))
    op.add_column('lesson_sessions', sa.Column('language_chosen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_sessions', 'language_chosen_at')
    op.drop_column('lesson_sessions', 'language_level')
    op.drop_column('lesson_sessions', 'language_mode')
    # ### end Alembic commands ###
