"""add_ai_admin_assistant_tables

Revision ID: 65532068a8dd
Revises: 0862b894e9ac
Create Date: 2025-12-03 16:21:59.994502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '65532068a8dd'
down_revision: Union[str, Sequence[str], None] = '0862b894e9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_ai_conversations_admin_user_id'), 'admin_ai_conversations', ['admin_user_id'], unique=False)
    op.create_table('tutor_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('applies_to_student_id', sa.Integer(), nullable=True),
    sa.Column('applies_to_app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applies_to_student_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_rules_applies_to_student_id'), 'tutor_rules', ['applies_to_student_id'], unique=False)
    op.create_index(op.f('ix_tutor_rules_is_active'), 'tutor_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_tutor_rules_scope'), 'tutor_rules', ['scope'], unique=False)
    op.create_table('admin_ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['admin_ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_ai_messages_conversation_id'), 'admin_ai_messages', ['conversation_id'], unique=False)
    op.create_table('tutor_rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('changed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['tutor_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_rule_versions_rule_id'), 'tutor_rule_versions', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_rule_versions_rule_id'), table_name='tutor_rule_versions')
    op.drop_table('tutor_rule_versions')
    op.drop_index(op.f('ix_admin_ai_messages_conversation_id'), table_name='admin_ai_messages')
    op.drop_table('admin_ai_messages')
    op.drop_index(op.f('ix_tutor_rules_scope'), table_name='tutor_rules')
    op.drop_index(op.f('ix_tutor_rules_is_active'), table_name='tutor_rules')
    op.drop_index(op.f('ix_tutor_rules_applies_to_student_id'), table_name='tutor_rules')
    op.drop_table('tutor_rules')
    op.drop_index(op.f('ix_admin_ai_conversations_admin_user_id'), table_name='admin_ai_conversations')
    op.drop_table('admin_ai_conversations')
    # ### end Alembic commands ###
